#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'application_ruby'
cookbook 'apt'
cookbook 'user'
cookbook 'ruby_build'
cookbook "mysql", "~> 6.0"
cookbook "mysql2_chef_gem", "~> 1.0.1"
cookbook "database", "~> 4.0.3"
cookbook "nodejs"

# cookbook 'railsbox', '~> 0.1.0'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
