#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# server base cookbooks
cookbook 'ubuntu'
cookbook 'users'
cookbook 'user', :git => 'ssh://git@github.com/fnichol/chef-user.git'
cookbook 'sudo'
cookbook 'apt'
cookbook 'git'
cookbook 'vim'
cookbook 'build-essential'
cookbook 'ntp'
cookbook 'chef-solo-search', :git => 'https://github.com/edelight/chef-solo-search.git'
cookbook 'ruby_build'

#rails server cookbooks
cookbook 'nginx'
cookbook 'rails_nginx_unicorn', :git => "https://github.com/substantial/cookbook-rails_nginx_unicorn.git", :ref => 'feature/no-rvm'

#database server cookbooks
cookbook 'mysql', "< 6.0"
cookbook 'database'
