name             'blog'
maintainer       'aja'
maintainer_email 'thagomizer@google.com'
license          'All rights reserved'
description      'Installs/Configures blog'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'application'
depends          'application_ruby'
depends          'mysql'
depends          'mysql2_chef_gem'
depends          'database'
